version: '3'
services:
  stumpy-service:
    container_name: stumpy-service
    build:
      context: .
      dockerfile: Dockerfile
    image: stumpy-service:latest
    entrypoint: java -jar -Dspring.profiles.active=prod /opt/stumpy-service/lib/stumpy-service.jar
    ports:
    - 8081:8081
    volumes:
    - stumpy-service-log-repo:/var/log/
    network_mode: "host"
    depends_on:
    - redis
    logging:
      driver: json-file
  redis:
    image: redis:alpine
    container_name: redis
    expose:
    - 6379
    ports:
    - 6379:6379
volumes:
  stumpy-service-log-repo:
    external: true